"""Add notification models

Revision ID: ca51b8f137ef
Revises: f6fa824eec2f
Create Date: 2026-07-04 23:09:58.204334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca51b8f137ef'
down_revision: Union[str, Sequence[str], None] = 'f6fa824eec2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=1024), nullable=True),
    sa.Column('metadata_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('user_notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_product_updates', sa.Boolean(), nullable=False),
    sa.Column('email_subscription_billing', sa.Boolean(), nullable=False),
    sa.Column('email_security_alerts', sa.Boolean(), nullable=False),
    sa.Column('email_marketing', sa.Boolean(), nullable=False),
    sa.Column('inapp_product_updates', sa.Boolean(), nullable=False),
    sa.Column('inapp_subscription_billing', sa.Boolean(), nullable=False),
    sa.Column('inapp_security_alerts', sa.Boolean(), nullable=False),
    sa.Column('inapp_marketing', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notification_preferences')
    op.drop_index('idx_notifications_user_read', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
